language: node_js

node_js:
  - "0.11"
  - "0.10"

before_script:
  node node_modules/jison/lib/cli.js lib/parser.jison -o lib/parser.js -t

after_success:
  cat coverage/lcov.info | node node_modules/coveralls/bin/coveralls.js